<a href="https://colab.research.google.com/github/nilangi-ediri/Machine-Learning-/blob/main/Assignment_2_Nilangi_E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cp
import numpy as np
import pandas as pd

def load_data_from_csv(file_name):
    data = pd.read_csv(file_name)
    labels = data.iloc[:,0].values
    labels = np.where(labels==0,-1,labels)
    features = data.iloc[:,1:].values
    return features, labels

def svm_train_primal ( data_train , label_train , regularisation_para_C ):
    m,n = data_train.shape

    w=cp.Variable(n)
    b=cp.Variable()
    si=cp.Variable(m)
    objective_function=cp.Minimize(0.5*cp.norm(w,2)**2+(regularisation_para_C/m)*cp.sum(si))
    constraints=[cp.multiply(label_train,data_train@w+b)>=(1-si),si>=0]
    optimization_problem=cp.Problem(objective_function,constraints)
    optimization_problem.solve()

    svm_model = {
        "w":w.value,
        "b":b.value,
         }

    return svm_model

def svm_predict_primal ( data_test , label_test , svm_model ):
    w=svm_model["w"]
    b=svm_model["b"]
    predictions = np.sign(data_test@w+b)
    accuracy = np.mean(predictions==label_test)*100
    return accuracy

data_train, label_train = load_data_from_csv("/train.csv")
data_test, label_test = load_data_from_csv("/test.csv")

## Setting training data size to 4000 samples as instructed
train_size = 4000
data_train_subset = data_train[:train_size]
label_train_subset = label_train[:train_size]

data_validation_subset = data_train[train_size:]
label_validation_subset = label_train[train_size:]

svm_model = svm_train_primal ( data_train_subset , label_train_subset , 100 )
test_accuracy = svm_predict_primal ( data_test , label_test , svm_model )
w_primal = svm_model["w"]
b_primal = svm_model["b"]
print("solution of b:", b_primal)
print("sum of all dimensions of w solution:", np.sum(w_primal))
print("test_accuracy %:", test_accuracy)

solution of b: 1.7870065517754259
sum of all dimensions of w solution: -0.2713847619329983
test_accuracy %: 96.93128752501667


In [ ]:
import cvxpy as cp
import numpy as np
import pandas as pd

def load_data_from_csv(file_name):
    data = pd.read_csv(file_name)
    labels = data.iloc[1:,0].values
    labels = np.where(labels==0,-1,labels)
    features = data.iloc[1:,1:].values
    return features, labels

def svm_train_primal ( data_train , label_train , regularisation_para_C ):
    m,n = data_train.shape

    w=cp.Variable(n)
    b=cp.Variable()
    si=cp.Variable(m)
    objective_function=cp.Minimize(0.5*cp.norm(w,2)**2+(regularisation_para_C/m)*cp.sum(si))
    constraints=[cp.multiply(label_train,data_train@w+b)>=(1-si),si>=0]
    optimization_problem=cp.Problem(objective_function,constraints)
    optimization_problem.solve()

    svm_model = {
        "w":w.value,
        "b":b.value,
         }

    return svm_model

def svm_predict_primal ( data_test , label_test , svm_model ):
    w=svm_model["w"]
    b=svm_model["b"]
    predictions = np.sign(data_test@w+b)
    accuracy = np.mean(predictions==label_test)*100
    return accuracy

data_train, label_train = load_data_from_csv("/content/train.csv")
data_test, label_test = load_data_from_csv("/content/test.csv")

## Setting training data size to 4000 samples as instructed
train_size = 4000
data_train_subset = data_train[:train_size]
label_train_subset = label_train[:train_size]

data_validation_subset = data_train[train_size:]
label_validation_subset = label_train[train_size:]

svm_model = svm_train_primal ( data_train_subset , label_train_subset , 100 )
test_accuracy = svm_predict_primal ( data_test , label_test , svm_model )
w_primal = svm_model["w"]
b_primal = svm_model["b"]
print("solution of b:", b_primal)
print("sum of all dimensions of w solution:", np.sum(w_primal))
print("test_accuracy %:", test_accuracy)

solution of b: 1.7870065527010477
sum of all dimensions of w solution: -0.2713847651065925
test_accuracy %: 96.92923898531375


In [ ]:
import cvxopt
import cvxopt.solvers
from cvxopt import matrix
from cvxopt import solvers

def svm_train_dual(data_train, label_train, regularisation_para_C):
    m, n = data_train.shape

    # Calculating the dot product of the data
    dot_product = np.dot(data_train, data_train.T)

    # Converting data to cvxopt matrices
    P = matrix(np.outer(label_train, label_train) * dot_product)
    q = matrix(-np.ones(m))

    # Setting up the constraints:
    G = matrix(np.vstack((-np.eye(m), np.eye(m))))
    h = matrix(np.hstack((np.zeros(m), np.ones(m) * regularisation_para_C)))

    A = matrix(label_train, (1, m), 'd')
    b = matrix(0.0)

    # Solving the quadratic problem
    solution = solvers.qp(P, q, G, h, A, b)

    alpha_value = np.ravel(solution['x'])

    svm_model_dual = {
        "alpha": alpha_value,
    }

    return svm_model_dual

svm_model_dual = svm_train_dual ( data_train_subset , label_train_subset , 100 )

print("alpha_values:",svm_model_dual["alpha"])

print("sum of all dimensions of the optimal alpha solution:", np.sum(svm_model_dual["alpha"]))

alpha = svm_model_dual["alpha"]

     pcost       dcost       gap    pres   dres
 0: -3.7283e+04 -3.5345e+07  1e+08  1e+00  6e-11
 1: -2.5207e+04 -1.2988e+07  2e+07  1e-01  5e-11
 2: -1.4749e+04 -4.1672e+06  6e+06  4e-02  4e-11
 3: -9.9947e+03 -1.7422e+06  2e+06  1e-02  4e-11
 4: -9.2237e+03 -7.2994e+05  9e+05  4e-03  4e-11
 5: -1.0924e+04 -2.4205e+05  2e+05  6e-04  4e-11
 6: -1.2293e+04 -8.1876e+04  7e+04  2e-04  4e-11
 7: -1.3188e+04 -6.5616e+04  5e+04  1e-04  4e-11
 8: -1.3188e+04 -6.3708e+04  5e+04  7e-05  4e-11
 9: -1.3834e+04 -5.2014e+04  4e+04  4e-05  4e-11
10: -1.4714e+04 -4.1835e+04  3e+04  2e-05  5e-11
11: -1.5405e+04 -3.7422e+04  2e+04  1e-05  5e-11
12: -1.5732e+04 -3.4712e+04  2e+04  9e-06  5e-11
13: -1.6325e+04 -3.0930e+04  1e+04  6e-06  5e-11
14: -1.6652e+04 -2.8737e+04  1e+04  4e-06  5e-11
15: -1.7029e+04 -2.6729e+04  1e+04  2e-06  6e-11
16: -1.7492e+04 -2.4885e+04  7e+03  1e-06  6e-11
17: -1.7812e+04 -2.3828e+04  6e+03  7e-07  6e-11
18: -1.8341e+04 -2.2350e+04  4e+03  3e-07  7e-11
19: -1.8453e+04 -2.19

In [ ]:
regularisation_para_C = 100

def calculate_w_b (alpha,data_train,label_train):
    m,n = data_train.shape
    w = np.sum(alpha[:, np.newaxis] * label_train[:, np.newaxis] * data_train, axis=0)
    support_vector_indices = (alpha>1e-5) & (alpha<regularisation_para_C/m) #Here 1e-5 fixes the rounding error in Python - alpha>0
    support_vectors = data_train[support_vector_indices]
    support_labels = label_train[support_vector_indices]
    b = np.mean(support_labels - np.dot(support_vectors, w))
    return w,b

w_dual,b_dual = calculate_w_b(alpha,data_train_subset,label_train_subset)

print("solution of b from dual:", b_dual)
print("sum of all dimensions of w solution from dual:", np.sum(w_dual))
print("solution of w from dual:", w_dual)


solution of b from dual: 2.9720025258306513
sum of all dimensions of w solution from dual: -0.15719023146272093
solution of w from dual: [ 9.45621118e-03 -1.70759366e-01  9.20691146e-02 -7.15859259e-02
  1.21314351e-01 -1.23895206e-01 -2.31701574e-02 -9.99884004e-02
  9.99544093e-02 -1.29327518e-02  2.03353070e-01  1.10539387e-01
  1.28142333e-02  1.80748553e-01  3.32349909e-02 -1.32511566e-01
 -1.41050407e-01 -1.81981120e-02 -1.46128893e-01 -3.41279225e-02
  6.61848270e-03  1.62974496e-01  1.08065881e-01 -8.06418838e-03
 -9.29391944e-03 -1.80520630e-02 -5.32170663e-02  1.82866164e-02
 -1.98241166e-01  2.27589737e-01 -1.19591687e-01 -5.02491848e-02
  6.08133436e-02 -7.33519195e-02  1.76780681e-01 -9.36579414e-02
 -3.02762463e-02 -1.24022115e-01  1.52388544e-01 -5.27707821e-02
  1.00933622e-02  8.75880859e-02 -1.18236883e-01  6.37163243e-02
  4.91217995e-02 -6.28458130e-02  2.50574372e-01  4.64866384e-02
  1.82992582e-01  1.97948871e-01 -1.16891327e-01 -1.96800887e-02
  7.92332106e-02 -

In [ ]:
def find_support_vectors_primal(w,b,data_train, label_train, epsilon):
   decision_value = np.dot(data_train,w) + b
   decision_margin = np.abs(label_train * decision_value -1) #This condition ensures points lie very close to the margin
   support_vector_indices = np.where(decision_margin < epsilon)
   return support_vector_indices, data_train[support_vector_indices], label_train[support_vector_indices]

##epsilon can be adjusted to reduce error margin when calculating support vectors
support_vector_indices_primal, support_vectors_primal, support_labels_primal = find_support_vectors_primal(w_primal,b_primal,data_train_subset,label_train_subset,epsilon=1e-10)
print("Total number of support vectors from primal:", len(support_vectors_primal))
print("Support vector indices from primal:",support_vector_indices_primal)
print("Support vectors from primal:",support_vectors_primal)
print("Support labels from primal:",support_labels_primal)

Total number of support vectors from primal: 22
Support vector indices from primal: (array([  15,  238,  546,  708,  795,  820,  842,  988, 1122, 1492, 1538,
       1591, 1626, 1779, 1824, 1889, 2144, 2644, 2750, 3283, 3739, 3868]),)
Support vectors from primal: [[ 1.05 -1.79  0.9  ...  0.39  0.6  -1.66]
 [ 0.38  2.13 -0.66 ...  0.21  2.36  0.49]
 [-0.18 -0.01 -2.21 ... -0.28 -0.37 -0.69]
 ...
 [-0.02  1.19  0.96 ...  2.27  0.22  0.82]
 [ 0.53  1.21 -0.08 ...  1.72 -0.49 -0.29]
 [ 1.24  0.29 -0.36 ... -0.67  1.79 -1.82]]
Support labels from primal: [ 1. -1. -1. -1. -1.  1. -1. -1.  1. -1.  1. -1.  1. -1. -1. -1. -1.  1.
  1. -1. -1.  1.]


In [ ]:
regularisation_para_C = 100
def find_support_vectors_dual(alpha,data_train,label_train, epsilon):
    m,n = data_train.shape
    support_vector_indices =np.where((alpha>epsilon) & (alpha<regularisation_para_C/m)) #Here epsilon fixes the rounding error in Python - alpha>0
    support_vectors = data_train[support_vector_indices]
    support_labels = label_train[support_vector_indices]

    return support_vector_indices, data_train[support_vector_indices], label_train[support_vector_indices]


support_vector_indices_dual, support_vectors_dual, support_labels_dual = find_support_vectors_dual(alpha,data_train_subset,label_train_subset,epsilon=1e-6)
print("Total number of support vectors from dual:", len(support_vectors_dual))
print("support vector indices from dual:",support_vector_indices_dual)
print("support vectors from dual:",support_vectors_dual)
print("support labels from dual:",support_labels_dual)

Total number of support vectors from dual: 21
support vector indices from dual: (array([  28,  155,  167,  328,  458,  594,  605,  707,  820,  992, 1178,
       1756, 1858, 1954, 2517, 2690, 2727, 3330, 3682, 3915, 3968]),)
support vectors from dual: [[ 0.41 -0.19  0.88 ... -1.56  0.48 -0.23]
 [-1.4  -0.55  0.17 ... -1.57  0.11  1.29]
 [ 0.26  0.15 -1.63 ...  1.01  1.43  1.78]
 ...
 [-0.02 -0.04 -0.29 ... -0.24 -0.83  1.04]
 [ 0.15 -0.74  1.07 ...  0.51 -0.69 -0.36]
 [ 0.79  1.01  1.2  ...  0.85 -0.97  0.98]]
support labels from dual: [ 1. -1.  1.  1.  1.  1.  1. -1.  1.  1. -1.  1.  1.  1.  1. -1. -1.  1.
 -1. -1.  1.]


In [ ]:
def validate_svm(data_train,label_train,data_validation,label_validation,C_values):
  validation_accuracies = []
  for C in C_values:
    svm_model = svm_train_primal(data_train, label_train, C)
    validation_accuracy = svm_predict_primal(data_validation, label_validation, svm_model)
    validation_accuracies.append(validation_accuracy)
    print(f'Validation accuracy for C = {C} : {validation_accuracy:.2f}%')
  return validation_accuracies
C_values =[2**i for i in range(-10,11,2)]
validation_accuracies = validate_svm(data_train_subset,label_train_subset,data_validation_subset,label_validation_subset,C_values)
best_C_index = np.argmax(validation_accuracies)
best_C = C_values[best_C_index]
print(f'Best C value: {best_C}')

Validation accuracy for C = 0.0009765625 : 49.10%
Validation accuracy for C = 0.00390625 : 49.10%
Validation accuracy for C = 0.015625 : 49.10%
Validation accuracy for C = 0.0625 : 92.49%
Validation accuracy for C = 0.25 : 96.22%
Validation accuracy for C = 1 : 97.18%
Validation accuracy for C = 4 : 97.47%
Validation accuracy for C = 16 : 97.40%
Validation accuracy for C = 64 : 97.04%
Validation accuracy for C = 256 : 96.51%
Validation accuracy for C = 1024 : 96.44%
Best C value: 4


In [ ]:
C_values =[i for i in range(1,16)]
validation_accuracies = validate_svm(data_train_subset,label_train_subset,data_validation_subset,label_validation_subset,C_values)
best_C_index = np.argmax(validation_accuracies)
best_C = C_values[best_C_index]
print(f'Best C value: {best_C}')

Validation accuracy for C = 1 : 97.18%
Validation accuracy for C = 2 : 97.35%
Validation accuracy for C = 3 : 97.24%
Validation accuracy for C = 4 : 97.47%
Validation accuracy for C = 5 : 97.49%
Validation accuracy for C = 6 : 97.53%
Validation accuracy for C = 7 : 97.44%
Validation accuracy for C = 8 : 97.51%
Validation accuracy for C = 9 : 97.53%
Validation accuracy for C = 10 : 97.49%
Validation accuracy for C = 11 : 97.53%
Validation accuracy for C = 12 : 97.51%
Validation accuracy for C = 13 : 97.49%
Validation accuracy for C = 14 : 97.49%
Validation accuracy for C = 15 : 97.47%
Best C value: 6


In [ ]:
from sklearn.svm import LinearSVC
svm_model_sk_learn = LinearSVC(C=best_C,dual="auto")
svm_model_sk_learn.fit(data_train_subset, label_train_subset)#training the model
predictions_sk_learn = svm_model_sk_learn.predict(data_test)
accuracy = np.mean(predictions_sk_learn==label_test)*100
print("test_accuracy %:", test_accuracy)

test_accuracy %: 96.93128752501667
